{{- if .Values.docker.registryUrl }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubenab.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kubenab.name" . }}
    helm.sh/chart: {{ include "kubenab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kubenab.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kubenab.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: {{ include "kubenab.fullname" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DOCKER_REGISTRY_URL
              value: {{ .Values.docker.registryUrl }}
            - name: REGISTRY_SECRET_NAME
              value: {{ .Values.docker.registrySecret }}
            - name: WHITELIST_NAMESPACES
              value: {{ .Values.whitelistNamespaces }}
            - name: WHITELIST_REGISTRIES
              value: {{ .Values.whitelistRegistries }}
            - name: REPLACE_REGISTRY_URL
              value: {{ .Values.docker.replaceRegistryUrl }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: tls
              mountPath: /etc/admission-controller/tls
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: tls
          secret:
            secretName: {{ .Values.tls.secretName | default (printf "%s" ( include "kubenab.servingCertificate" .)) }}
{{- end }}
