apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "kubenab.fullname" . }}
  labels:
    app: {{ template "kubenab.name" . }}
    chart: {{ template "kubenab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kubenab.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kubenab.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DOCKER_REGISTRY_URL
              value: {{ .Values.docker.registryUrl }}
            - name: REGISTRY_SECRET_NAME
              value: {{ .Values.docker.registrySecret }}
            - name: WHITELIST_NAMESPACES
              value: {{ .Values.whitelistNamespaces }}
            - name: WHITELIST_REGISTRIES
              value: {{ .Values.whitelistRegistries }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
          - name: tls
            mountPath: /etc/admission-controller/tls
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: tls
          secret:
            secretName: {{ .Values.tlsSecretName }}