{{- if .Values.mutatingWebhook.enabled -}}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kubenab.fullname" . }}-mutate
  labels:
{{ include "kubenab.labels" . | indent 4 }}
  annotations:
    certmanager.k8s.io/inject-ca-from: "{{ .Release.Namespace }}/{{ include "kubenab.servingCertificate" . }}"
webhooks:
- name: kubenab-mutate.k8s.io
  rules:
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  failurePolicy: Ignore
  clientConfig:
    service:
      name: {{ include "kubenab.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: "/mutate"
{{- end -}}
