version: 2
jobs:
  untagged-build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/jfrog/kubenab
    steps:
      - checkout
      - run: make build
workflows:
  version: 2
  untagged-build:
    jobs:
      - untagged-build
