apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: kubenab-validate
webhooks:
- name: kubenab-validate.kubenab.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  failurePolicy: Ignore
  clientConfig:
    service:
      name: kubenab
      namespace: default
      path: "/validate"
    caBundle: ${CA_BUNDLE}
