apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: kubenab-mutate
webhooks:
- name: kubenab-mutate.kubenab.com
  rules:
  - operations: [ "CREATE", "UPDATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  failurePolicy: Ignore
  clientConfig:
    service:
      name: kubenab
      namespace: default
      path: "/mutate"
    caBundle: ${CA_BUNDLE}
