resources:
  - name: kubenab_pr
    type: GitRepo
    configuration:
      gitProvider: jfrogsolutionsci_github
      path: jfrog/kubenab
      files:
        exclude: .pipelines/.*.yml$
      branches:
        exclude: master
      buildOn:
        commit: false
        pullRequestCreate: true

pipelines:
  - name: kubenabPr
    steps:
      - name: build_image_pr
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: kubenab
          dockerImageTag: $run_number
          inputResources:
            - name: kubenab_pr
          integrations:
            - name: cpe_pipeline_slack
        execution:
          onStart:
            - send_notification cpe_pipeline_slack --text "Starting kubenabPr ${step_name}_buildNumber=${run_number}" 
          onSuccess:
            - send_notification cpe_pipeline_slack --text "kubenabPr ${step_name}_buildNumber=${run_number} - SUCCESS"
          onFailure:
            - send_notification cpe_pipeline_slack --text "kubenabPr ${step_name}_buildNumber=${run_number} - FAILED"
