# Default values for kubenab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets:

image:
  repository: docker.bintray.io/kubenab
  # Note that by default we use appVersion to get image tag
  # tag:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 443

docker:
  registryUrl:
  registrySecret: regsecret

# Whitelist namespaces e.g "kubesystem,default,development"
whitelistNamespaces: "kube-system,cert-manager"
# Whitelist docker registries within non-whitelisted namespaces e.g "rimusz,10.110.50.0:5000,docker.artifactory.com"
whitelistRegistries:

# Set external secret for TLS certs, it disables SelfSigned certs from the cert-manager
# Run script tls/gen-cert.sh to generate TLS certs and store them in kubenab-tls secret
tls:
  secretName: # kubenab-tls

# Use ValidatingAdmissionWebhook only if you want to check pulling 
# of docker image from a Private Docker Registry e.g JFrog Artifactory. 
# If your container image does not contain REGISTRY_URL then Kubetug will deny request to run that pod.
validatingWebhook:
  enabled: true

# Use MutatingAdmissionWebhook only if you want to enforce pulling 
# of docker image from a Private Docker Registry e.g JFrog Artifactory. 
# If your container image is nginx then Kubetug  will append REGISTRY_URL to it. e.g nginx will become someregistry/nginx
mutatingWebhook:
  enabled: false

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

## Role Based Access Control
rbac:
  create: true
  role:
    ## Rules to create. It follows the role specification
    rules:
    - apiGroups:
      - ''
      resources:
      - services
      - endpoints
      - pods
      verbs:
      - get
      - watch
      - list

affinity: {}

tolerations: []

nodeSelector: {}
